buildImage = 'ghcr.io\/railwayapp\/nixpacks:ubuntu-1725321821'

[variables]
PM_CONFIG_PRODUCTION = 'true'
CI = 'true'
NIXPACKS_METADATA = 'node'
NIXPACKS_NODE_VERSION = '22'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'

[phases.build]
dependsOn = ['install']
cmds = ['bun _build']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['bun install --production --frozen-lockfile']
cacheDirectories = ['/root/.bun']
paths = ['/app/node_modules/.bin']

[phases.setup]
# https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/bu/bun/package.nix
nixpkgsArchive = 'd05592ea7e9656648093dfe0e817819486bd5054' # https://github.com/NixOS/nixpkgs/commit/18587d60c47d93e4b8a4c7b959a8e1f7535c04f7
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
#nixPkgs = ['nodejs_22']
aptPackages = ['curl', 'wget']

[start]
cmd = 'node ./dist/server.js'
