name: checks
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  biome:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: cycodelabs/cimon-action@v0
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          fail_on_error: true

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
      - uses: actions/checkout@v4
      - run: bun install
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: github-pr-review

  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
      - name: Check out code.
        uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
      - uses: actions/checkout@v4
      - uses: reviewdog/action-typos@v1

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
      - uses: actions/checkout@v4
      - run: bun add stylelint stylelint-config-recommended -D
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review

  bearer:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: rdjson
          output: rd.json
          diff: true
      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat rd.json | reviewdog -f=rdjson -reporter=github-pr-review

# check:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v4
#     - uses: oven-sh/setup-bun@v2
#     - run: bun ci
