name: check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - run: bun ci
