name: checks
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

env:
  REPORTER_TYPE: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          allowed-hosts: >
            api.cycode.com github.com api.github.com codeload.github.com objects.githubusercontent.com registry.npmjs.org bun.sh
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          fail_on_error: true
          reporter: ${{ env.REPORTER_TYPE }}

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          allowed-hosts: >
            api.cycode.com github.com api.github.com codeload.github.com objects.githubusercontent.com registry.npmjs.org bun.sh
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: ${{ env.REPORTER_TYPE }}

  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          allowed-hosts: >
            api.cycode.com github.com api.github.com codeload.github.com objects.githubusercontent.com registry.npmjs.org bun.sh
      - name: Check out code.
        uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          reporter: ${{ env.REPORTER_TYPE }}

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          allowed-hosts: >
            api.cycode.com github.com api.github.com codeload.github.com objects.githubusercontent.com raw.githubusercontent.com
      - uses: actions/checkout@v4
      - uses: reviewdog/action-typos@v1
        with:
          reporter: ${{ env.REPORTER_TYPE }}

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          allowed-hosts: >
            api.cycode.com github.com api.github.com codeload.github.com objects.githubusercontent.com registry.npmjs.org bun.sh
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun add stylelint stylelint-config-recommended -D
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: ${{ env.REPORTER_TYPE }}

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          allowed-hosts: >
            api.cycode.com github.com api.github.com codeload.github.com objects.githubusercontent.com registry.npmjs.org bun.sh
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: ${{ env.REPORTER_TYPE }}

  bearer:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          prevent: true
          allowed-hosts: >
            api.cycode.com github.com api.github.com codeload.github.com objects.githubusercontent.com raw.githubusercontent.com
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: rdjson
          output: rd.json
          diff: true
      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat rd.json | reviewdog -f=rdjson -reporter=${{ env.REPORTER_TYPE }}
        #-level=error

# https://github.com/Araxeus/opl-whatsapp-server/actions/runs/9923702398

# check:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v4
#     - uses: oven-sh/setup-bun@v2
#     - run: bun ci

